In [4]:
import pandas as pd
from pathlib import Path
import os

In [7]:
NOTEBOOK_DIR = Path(os.getcwd()).resolve()
PROJECT_DIR = NOTEBOOK_DIR.parent
RAW_DATA_DIR = PROJECT_DIR / "data" / "raw"

In [8]:
df_trends = pd.read_parquet(RAW_DATA_DIR / "google_trends.parquet")

In [9]:
df_trends.head()

        date region   brand  trend_index
0 2026-01-01     AU  Adidas           75
1 2026-01-02     AU  Adidas           72
2 2026-01-03     AU  Adidas           68
3 2026-01-04     AU  Adidas           65
4 2026-01-05     AU  Adidas           64

In [11]:
df_trends.info()

<class 'pandas.DataFrame'>
RangeIndex: 15750 entries, 0 to 15749
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         15750 non-null  datetime64[ms]
 1   region       15750 non-null  str
 2   brand        15750 non-null  str
 3   trend_index  15750 non-null  int64
dtypes: datetime64[ms](1), int64(1), str(2)
memory usage: 624.6 KB

In [27]:
pd.Series(df_trends[['region', 'brand']].value_counts().to_list()).value_counts()

90    175
Name: count, dtype: int64

In [14]:
df_retail = pd.read_csv(RAW_DATA_DIR / "retail_pricing_demand_100k.csv")
df_retail.head()

,date,product_id,category,brand,region,channel,season,base_price,current_price,price_change_pct,discount_pct,promotion_type,units_sold,revenue,inventory_level,stockout_flag,demand_index
0,2026-01-01,P1001,Shoes,Nike,AU,mobile,Winter,173.55,112.81,-35.0,35,Buy One Get One,15,1692.15,153,0,133.93
1,2026-01-02,P1001,Shoes,Nike,AU,web,Winter,173.55,173.55,0.0,0,NaN,10,1735.50,185,0,89.29
2,2026-01-03,P1001,Shoes,Nike,AU,app,Winter,173.55,173.55,0.0,0,NaN,13,2256.15,312,0,116.07
3,2026-01-04,P1001,Shoes,Nike,AU,web,Winter,173.55,164.87,-5.0,5,Member Offer,13,2143.31,227,0,116.07
4,2026-01-05,P1001,Shoes,Nike,AU,app,Winter,173.55,173.55,0.0,0,NaN,13,2256.15,247,0,116.07

In [34]:
df_grouped = df_trends.groupby(['region', 'brand'])['trend_index'].transform('mean')
df_grouped = df_trends.groupby(['region', 'brand'])['trend_index'].transform('std')
df_grouped

0         9.972897
1         9.972897
2         9.972897
3         9.972897
4         9.972897
           ...
15745    13.809819
15746    13.809819
15747    13.809819
15748    13.809819
15749    13.809819
Name: trend_index, Length: 15750, dtype: float64